devases_setup = [
    {
        "name": "ИП535-07еа-RS",
        "slave": 1,
        "baudrate": 19200,
        "stopbit": 2,
        "stopbits": 1,
        "register_slave": 0,
        "register_baudrate": 1,
        "register_stopbit": 2,
        "register_stopbits": 3,
    },
    {
        "name": "ИП535-07еа-RS-“ПУСК”",
        "slave": 1,
        "baudrate": 19200,
        "stopbit": 2,
        "stopbits": 1,
        "register_slave": 0,
        "register_baudrate": 1,
        "register_stopbit": 2,
        "register_stopbits": 3,
    },
    {
        "name": "ИП101-07а-RS",
        "slave": 1,
        "baudrate": 19200,
        "stopbit": 2,
        "stopbits": 1,
        "register_slave": 0,
        "register_baudrate": 1,
        "register_stopbit": 2,
        "register_stopbits": 3,
    }
]