from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QGroupBox,
    QHeaderView, QLabel, QLineEdit, QPushButton,
    QSizePolicy, QTableWidget, QTableWidgetItem, QWidget)

class Ui_form_scan(object):
    def setupUi(self, form_scan):
        if not form_scan.objectName():
            form_scan.setObjectName(u"form_scan")
        form_scan.resize(571, 485)
        self.comboBox_com_port = QComboBox(form_scan)
        self.comboBox_com_port.setObjectName(u"comboBox_com_port")
        self.comboBox_com_port.setGeometry(QRect(80, 10, 251, 22))
        self.com_port = QLabel(form_scan)
        self.com_port.setObjectName(u"com_port")
        self.com_port.setGeometry(QRect(20, 10, 51, 16))
        font = QFont()
        font.setBold(True)
        self.com_port.setFont(font)
        self.group_box_slave = QGroupBox(form_scan)
        self.group_box_slave.setObjectName(u"group_box_slave")
        self.group_box_slave.setGeometry(QRect(20, 40, 211, 51))
        self.group_box_slave.setFont(font)
        self.etr_slave_to = QLineEdit(self.group_box_slave)
        self.etr_slave_to.setObjectName(u"etr_slave_to")
        self.etr_slave_to.setGeometry(QRect(160, 20, 41, 20))
        font1 = QFont()
        font1.setBold(False)
        self.etr_slave_to.setFont(font1)
        self.lbl_from = QLabel(self.group_box_slave)
        self.lbl_from.setObjectName(u"lbl_from")
        self.lbl_from.setGeometry(QRect(10, 20, 43, 13))
        self.lbl_from.setFont(font1)
        self.lbl_to = QLabel(self.group_box_slave)
        self.lbl_to.setObjectName(u"lbl_to")
        self.lbl_to.setGeometry(QRect(130, 20, 21, 16))
        self.lbl_to.setFont(font1)
        self.etr_slave_from = QLineEdit(self.group_box_slave)
        self.etr_slave_from.setObjectName(u"etr_slave_from")
        self.etr_slave_from.setGeometry(QRect(40, 20, 41, 20))
        self.etr_slave_from.setFont(font1)
        self.groupBox_speeds = QGroupBox(form_scan)
        self.groupBox_speeds.setObjectName(u"groupBox_speeds")
        self.groupBox_speeds.setGeometry(QRect(240, 40, 91, 231))
        self.checkBox_1200 = QCheckBox(self.groupBox_speeds)
        self.checkBox_1200.setObjectName(u"checkBox_1200")
        self.checkBox_1200.setGeometry(QRect(10, 20, 62, 17))
        self.checkBox_2400 = QCheckBox(self.groupBox_speeds)
        self.checkBox_2400.setObjectName(u"checkBox_2400")
        self.checkBox_2400.setGeometry(QRect(10, 40, 62, 17))
        self.checkBox_4800 = QCheckBox(self.groupBox_speeds)
        self.checkBox_4800.setObjectName(u"checkBox_4800")
        self.checkBox_4800.setGeometry(QRect(10, 60, 62, 17))
        self.checkBox_9600 = QCheckBox(self.groupBox_speeds)
        self.checkBox_9600.setObjectName(u"checkBox_9600")
        self.checkBox_9600.setGeometry(QRect(10, 80, 62, 17))
        self.checkBox_14400 = QCheckBox(self.groupBox_speeds)
        self.checkBox_14400.setObjectName(u"checkBox_14400")
        self.checkBox_14400.setGeometry(QRect(10, 100, 62, 17))
        self.checkBox_19200 = QCheckBox(self.groupBox_speeds)
        self.checkBox_19200.setObjectName(u"checkBox_19200")
        self.checkBox_19200.setGeometry(QRect(10, 120, 62, 17))
        self.checkBox_28800 = QCheckBox(self.groupBox_speeds)
        self.checkBox_28800.setObjectName(u"checkBox_28800")
        self.checkBox_28800.setGeometry(QRect(10, 140, 62, 17))
        self.checkBox_38400 = QCheckBox(self.groupBox_speeds)
        self.checkBox_38400.setObjectName(u"checkBox_38400")
        self.checkBox_38400.setGeometry(QRect(10, 160, 62, 17))
        self.checkBox_57600 = QCheckBox(self.groupBox_speeds)
        self.checkBox_57600.setObjectName(u"checkBox_57600")
        self.checkBox_57600.setGeometry(QRect(10, 180, 62, 17))
        self.checkBox_115200 = QCheckBox(self.groupBox_speeds)
        self.checkBox_115200.setObjectName(u"checkBox_115200")
        self.checkBox_115200.setGeometry(QRect(10, 200, 62, 17))
        self.groupBox_parity = QGroupBox(form_scan)
        self.groupBox_parity.setObjectName(u"groupBox_parity")
        self.groupBox_parity.setGeometry(QRect(40, 100, 81, 80))
        self.check_box_none = QCheckBox(self.groupBox_parity)
        self.check_box_none.setObjectName(u"check_box_none")
        self.check_box_none.setGeometry(QRect(10, 20, 62, 17))
        self.check_box_even = QCheckBox(self.groupBox_parity)
        self.check_box_even.setObjectName(u"check_box_even")
        self.check_box_even.setGeometry(QRect(10, 40, 62, 17))
        self.check_box_odd = QCheckBox(self.groupBox_parity)
        self.check_box_odd.setObjectName(u"check_box_odd")
        self.check_box_odd.setGeometry(QRect(10, 60, 62, 17))
        self.groupBox_s_bits = QGroupBox(form_scan)
        self.groupBox_s_bits.setObjectName(u"groupBox_s_bits")
        self.groupBox_s_bits.setGeometry(QRect(140, 100, 81, 80))
        self.check_box_sb1 = QCheckBox(self.groupBox_s_bits)
        self.check_box_sb1.setObjectName(u"check_box_sb1")
        self.check_box_sb1.setGeometry(QRect(10, 20, 62, 17))
        self.check_box_sb15 = QCheckBox(self.groupBox_s_bits)
        self.check_box_sb15.setObjectName(u"check_box_sb15")
        self.check_box_sb15.setGeometry(QRect(10, 40, 62, 17))
        self.check_box_sb2 = QCheckBox(self.groupBox_s_bits)
        self.check_box_sb2.setObjectName(u"check_box_sb2")
        self.check_box_sb2.setGeometry(QRect(10, 60, 62, 17))
        self.pushButton_scan = QPushButton(form_scan)
        self.pushButton_scan.setObjectName(u"pushButton_scan")
        self.pushButton_scan.setGeometry(QRect(20, 190, 161, 81))
        self.table_devices = QTableWidget(form_scan)
        self.table_devices.setObjectName(u"table_devices")
        self.table_devices.setGeometry(QRect(20, 280, 311, 192))

        self.retranslateUi(form_scan)

        QMetaObject.connectSlotsByName(form_scan)
    # setupUi

    def retranslateUi(self, form_scan):
        form_scan.setWindowTitle(QCoreApplication.translate("form_scan", u"Form", None))
        self.com_port.setText(QCoreApplication.translate("form_scan", u"COM Port", None))
        self.group_box_slave.setTitle(QCoreApplication.translate("form_scan", u"Slave", None))
        self.etr_slave_to.setInputMask("")
        self.etr_slave_to.setText("")
        self.lbl_from.setText(QCoreApplication.translate("form_scan", u"From", None))
        self.lbl_to.setText(QCoreApplication.translate("form_scan", u"To", None))
        self.etr_slave_from.setInputMask("")
        self.etr_slave_from.setText("")
        self.groupBox_speeds.setTitle(QCoreApplication.translate("form_scan", u"Speed", None))
        self.checkBox_1200.setText(QCoreApplication.translate("form_scan", u"1200", None))
        self.checkBox_2400.setText(QCoreApplication.translate("form_scan", u"2400", None))
        self.checkBox_4800.setText(QCoreApplication.translate("form_scan", u"4800", None))
        self.checkBox_9600.setText(QCoreApplication.translate("form_scan", u"9600", None))
        self.checkBox_14400.setText(QCoreApplication.translate("form_scan", u"14400", None))
        self.checkBox_19200.setText(QCoreApplication.translate("form_scan", u"19200", None))
        self.checkBox_28800.setText(QCoreApplication.translate("form_scan", u"28800", None))
        self.checkBox_38400.setText(QCoreApplication.translate("form_scan", u"38400", None))
        self.checkBox_57600.setText(QCoreApplication.translate("form_scan", u"57600", None))
        self.checkBox_115200.setText(QCoreApplication.translate("form_scan", u"115200", None))
        self.groupBox_parity.setTitle(QCoreApplication.translate("form_scan", u"Parity", None))
        self.check_box_none.setText(QCoreApplication.translate("form_scan", u"None", None))
        self.check_box_even.setText(QCoreApplication.translate("form_scan", u"Even", None))
        self.check_box_odd.setText(QCoreApplication.translate("form_scan", u"Odd", None))
        self.groupBox_s_bits.setTitle(QCoreApplication.translate("form_scan", u"Stop Bits", None))
        self.check_box_sb1.setText(QCoreApplication.translate("form_scan", u"1", None))
        self.check_box_sb15.setText(QCoreApplication.translate("form_scan", u"1,5", None))
        self.check_box_sb2.setText(QCoreApplication.translate("form_scan", u"2", None))
        self.pushButton_scan.setText(QCoreApplication.translate("form_scan", u"Start Scan", None))
    # retranslateUi

